drop table if exists entries;
create table entries (
  id integer primary key autoincrement,
  'alias' text,
  'age' int,
  'income' bigint,
  'worth' bigint,
  'preference' text,
  'household' text,
  'action' text,
  'handle' text,
  'risk' int,
  'etf1' real,
  'etf2' real,
  'etf3' real,
  'etf4' real,
  'etf5' real,
  'etf6' real,
  'etf7' real,
  'etf8' real,
  'etf9' real,
  'etf10' int,
  'etf11' int,
  'etf12' int,
  'etf13' int,
  'etf14' int,
  'return' int,
  'vol' int
);
